### ISSUE TITLE
python小白请教下大佬使用方法

### ISSUE THREAD

**Issue by KalaMeetsT1** [ihopenot/LpkUnpacker#4]
请问如何配置位置参数呢，我尝试用Pycharm配置了一下，返回了以下提示：

TypeError: expected str, bytes or os.PathLike object, not NoneType

这是我在Pycharm中尝试的配置内容：
C:\Users\Downloads\LpkUnpacker-master\LpkUnpacker-master\xxx.lpk
C:\Users\Downloads\LpkUnpacker-master\LpkUnpacker-master

**Comment by WeihengFu** [comment]
Here is a fix without having to debug: 
1) go to directory of LpkUnpacker-master
2) put your lpk and config.json in a new folder called "lpk"
3) create a new folder called "new" which will contain all your unzipped files
4) change your LpkUnpacker.py into:
import sys
import argparse
from Core.lpk_loader import *
from Core.utils import *
loader = LpkLoader("./lpk/[Insert your lpk name here and delete bracket].lpk", "./lpk/config.json")
loader.extract("./new")
5) Use a text editor to open the config.json and copy it for use
6) Go to Core\lpkloader.py and change the 
self.config = json.loads(open(self.configpath, "r", encoding="utf8").read())
line into 
self.config = [replace with what you copied from step 5]
7) Add a line
self.config = {}
at line 18 just to be safe that it knows self.config is supposed to be dictionary
8) run LpkUnpacker.py and you should be able to get what you want in the folder.

P.S. the bug is very weird, at first I thought its just one simple directory issue (win error 123) but after fixing the class definition, traceback is telling me something is wrong with stuff I commented out which is rediculuous. That is why I have decided enough is enough and started stripping down  LpkUnpacker.py

PPS. Great work! Would be even better if there were another script to zip stuff back but thanks a lot!!!

**Comment by ihopenot** [comment]
> 请问如何配置位置参数呢，我尝试用Pycharm配置了一下，返回了以下提示：
> 
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> 这是我在Pycharm中尝试的配置内容： C:\Users\Downloads\LpkUnpacker-master\LpkUnpacker-master\xxx.lpk C:\Users\Downloads\LpkUnpacker-master\LpkUnpacker-master

你这个问题看起来是参数配错了，pycharm的话你要配置启动参数（命令行参数）。你只说配置内容我也不知道你到底配了个啥，但是看起来你是配歪了。

**Comment by ihopenot** [comment]
> 

你可以详细描述下你遇到的bug，另外这只是个解包工具，重打包可以用Live2dViewerEx自带的studio打包。

**Comment by KalaMeetsT1** [comment]
> > 
> 
> 你可以详细描述下你遇到的bug，另外这只是个解包工具，重打包可以用Live2dViewerEx自带的studio打包。

感谢作者！已经成功运行了！

**Comment by 2088722861** [comment]
> > > 
> > 
> > 
> > 你可以详细描述下你遇到的bug，另外这只是个解包工具，重打包可以用Live2dViewerEx自带的studio打包。
> 
> 感谢作者！已经成功运行了！

您好，有时间可以教教我这个小白怎么运行吗，想改图很久了，您加下我的qq2088722861

**Comment by 2088722861** [comment]
Hello, can you provide a video tutorial? Thank you very much, Xiao Bai. This is my game 2088722861@qq.com
